# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ImageAuditor < Formula
  desc "Finds & AI-fixes Lighthouse image issues (CLS, lazy loading, WebP, srcset) across your entire codebase in seconds."
  homepage "https://github.com/0franco/image-auditor"
  version "0.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/0franco/image-auditor/releases/download/v0.2.4/image-auditor_darwin_amd64.tar.gz"
      sha256 "2fe3ce42fe2c73429f9d501fbd31f646e8d863137e302bbb726324faf0c01ebc"

      define_method(:install) do
        bin.install "image-auditor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/0franco/image-auditor/releases/download/v0.2.4/image-auditor_darwin_arm64.tar.gz"
      sha256 "5d8868c08e1533e1d6cb7ab9de31a00178fd7f555ae079ab68b598e1847107ec"

      define_method(:install) do
        bin.install "image-auditor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/0franco/image-auditor/releases/download/v0.2.4/image-auditor_linux_amd64.tar.gz"
      sha256 "a4b1c5dbb7e7ae3191f8cf512e6fdd3301add0d1791f7fe0a5486ffa9d3ae87f"
      define_method(:install) do
        bin.install "image-auditor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0franco/image-auditor/releases/download/v0.2.4/image-auditor_linux_arm64.tar.gz"
      sha256 "2c36df84fe3c895396e2dd38b0ceedda0cd100eda2eb8249f86f9963bc816fb3"
      define_method(:install) do
        bin.install "image-auditor"
      end
    end
  end

  test do
    system "#{bin}/image-auditor", "--version"
  end
end
