# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ImageAuditor < Formula
  desc "Finds & AI-fixes Lighthouse image issues (CLS, lazy loading, WebP, srcset) across your entire codebase in seconds."
  homepage "https://github.com/0franco/image-auditor"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/0franco/image-auditor/releases/download/v0.2.1/image-auditor_darwin_amd64.tar.gz"
      sha256 "ea00081954b462d45e10c4225d82e7398b433edf785d25ff9b5ad550f371233e"

      define_method(:install) do
        bin.install "image-auditor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/0franco/image-auditor/releases/download/v0.2.1/image-auditor_darwin_arm64.tar.gz"
      sha256 "b37b4fc722ec7afd797933efe649424fac415c2f0cae05e2f059beee734db565"

      define_method(:install) do
        bin.install "image-auditor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/0franco/image-auditor/releases/download/v0.2.1/image-auditor_linux_amd64.tar.gz"
      sha256 "6b102ef4d01431470f87b44c4ffd19136ecb1d2baee8f935723a3dffc50974bd"
      define_method(:install) do
        bin.install "image-auditor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0franco/image-auditor/releases/download/v0.2.1/image-auditor_linux_arm64.tar.gz"
      sha256 "590ba547eecabc9ac2ae71aa2c6067c36f714deb62fa1702f5b85af5b091792f"
      define_method(:install) do
        bin.install "image-auditor"
      end
    end
  end

  test do
    system "#{bin}/image-auditor", "--version"
  end
end
